### PR TITLE
Adding a New Resourse Called Build a Desktop Application with Electron and Angular

### PR DESCRIPTION
**Pull request by shuaibabs**
Heyy There...

I'm Adding a new Resource Called Building an Image Gallery with Angular
this is my Favourite Resource

### CODE REVIEW

**Comment by timdeschryver** [comment]
@shuaibabs thanks for the PR, can you resolve the conflict please so we can merge this in?

**Comment by shuaibabs** [comment]
> @shuaibabs thanks for the PR, can you resolve the conflict please so we can merge this in?

Ok I'll Resolve this Conflict

**Comment by shuaibabs** [comment]
Could you please label this PR with the label "hacktoberfest-accepted" before you merge it? :)

**Comment by timdeschryver** [comment]
@shuaibabs I don't know what happened but it seems like the resources are copy pasted in the same json file.
Could you have a look at it, so it only contains your addition please?

**Comment by shuaibabs** [comment]
> @shuaibabs I don't know what happened but it seems like the resources are copy pasted in the same json file.
> Could you have a look at it, so it only contains your addition please?

i have ad another resources please check them.

**Comment by timdeschryver** [comment]
If you take a look at the `resources.json`, you can see that it's content isn't correct.
This is how the change should look like: https://github.com/timdeschryver/hacktoberfest-2019-angular/pull/178/files#diff-5628a864672d2fb4d97f63d20858ecfb7c82df899e798c44fa06d013ae084b28

**Comment by shuaibabs** [comment]
> If you take a look at the `resources.json`, you can see that it's content isn't correct.
> This is how the change should look like: https://github.com/timdeschryver/hacktoberfest-2019-angular/pull/178/files#diff-5628a864672d2fb4d97f63d20858ecfb7c82df899e798c44fa06d013ae084b28

So What i have to do for merge this PR ?

**Comment by timdeschryver** [comment]
Fix the resources files, the content is now duplicated.

**Comment by shuaibabs** [comment]
> Fix the resources files, the content is now duplicated.

I Have resolved resources.json, 
Now Please Merge this PR :)

**Pull request closed without merging**
