### PR TITLE
Resources are shuffled on page load and a random button

### PR DESCRIPTION
**Pull request by makitsune**

### CODE REVIEW

**Comment by makitsune** [comment]
Sure. I wasn't very sure how to best implement it since I dont use the async pipe

**Comment by timdeschryver** [comment]
Would you want to change the implementation to the proposed version?

**Comment by makitsune** [comment]
Okay. When I have time today or tomorrow, ill update it

**Comment by timdeschryver** [comment]
I have added a change to randomize the resources when the page is opened, see the commit f34a8686bbf68b86d2a7e8b82911192e5fcb4949.

**Pull request closed without merging**
